/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package task2;

import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel
 */
public class Server extends javax.swing.JFrame {

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btStart = new javax.swing.JButton();
        lbStatusServer = new javax.swing.JLabel();
        lbIpClient = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btStart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btStart.setText("Iniciar Sevidor");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        lbStatusServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStatusServer.setText("Status servidor");

        lbIpClient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbIpClient.setText("IP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btStart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lbStatusServer))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lbIpClient)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbIpClient)
                .addGap(55, 55, 55)
                .addComponent(btStart, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(lbStatusServer)
                .addGap(45, 45, 45))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        // TODO add your handling code here:

        lbStatusServer.setText("Servidor iniciado!");
        
        try {
            Server1 s = new Server1();
            s.iniciar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao iniciar servidor");
        }

    }//GEN-LAST:event_btStartActionPerformed

    public static String connectRemote(ArrayList data) throws RemoteException{
        
        String replyServer="";
        
        try {
            Registry reg = LocateRegistry.getRegistry("", 4444);
            Functions fun = (Functions) reg.lookup("h1_server");
            
            replyServer = fun.send(data);
            
            if(replyServer.equals("Primeiro registro!")){
                register(data);
            }
    
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(null, "Erro1: "+ e.getMessage());
        } catch (NotBoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro2: "+ ex.getMessage());
        }
        
        return replyServer;
        
    }
    
    public static int check(String password){
        
        int test=0;
        
        ArrayList<User> users = new ArrayList<>();
        UserDAO udao = new UserDAO();
        users = udao.retornaTodos();
        
        for(int i=0; i<users.size(); i++){
            if(users.get(i).getPassword().equals(password)){
                test=1;
            }
        }        
        
        return test;
        
    }
    
    public static void register(ArrayList data){
        
        String imc2 = (String) data.get(0);
        double imc = Double.parseDouble(imc2);
        String ip = (String) data.get(1);
        String password = (String) data.get(2);
        
        lbIpClient.setText(ip);
        
        if(check(password) == 0){
            User u = new User(imc, ip, password);
            UserDAO udao = new UserDAO();
            udao.adiciona(u);            
        } else{
            System.out.println("Já cadastrado!");
        }
            
        
    }
    
    public static void setIp(String ip){
        
        lbIpClient.setText(ip);
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel lbIpClient;
    private javax.swing.JLabel lbStatusServer;
    // End of variables declaration//GEN-END:variables
}
